baseURL = "https://maxmorris.io/"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
disableKinds = ["taxonomy", "term"]
theme = "lynx"

title = "Maxwell Morris"
copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Maxwell Morris"
  headline = "IT Consultant / Bristol, UK"
  image = "me.jpg"

  links = [
    { link = { href = "https://maxmorris.io/cv.pdf", text = "CV" } },
    { email = "mailto:site@maxmorris.io" },
    { pay = { href = "https://monzo.me/maxwellmorris", text = "Pay" } },
    { linkedin = "https://linkedin.com/in/maxwell-morris-728030212" },
    { github = "https://github.com/m4xmorris" },
    { telegram = "https://t.me/m4xm0rris" },
  ]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.86.1"
