version: 38
jobs:
- name: github-mirror
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: true
    withSubmodules: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PushRepository
    name: push-to-github
    remoteUrl: https://github.com/m4xmorris/maxmorris.io
    passwordSecret: github-pat
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: main
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: terraform-plan
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: true
    withSubmodules: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: terraform-plan
    runInContainer: true
    image: hashicorp/terraform:1.10
    interpreter: !DefaultInterpreter
      commands: |
        export TF_INPUT="false"
        export TF_IN_AUTOMATION="true"
        export TF_TOKEN_app_terraform_io="@secret:tf-token@"
        export TF_VAR_cloudflare_token="@secret:cloudflare-token@"
        export TF_VAR_cloudflare_account_id="@secret:cloudflare-account-id@"
        export TF_VAR_cloudflare_zone_id="@secret:cloudflare-zone-id@"

        cd terraform
        terraform init &&
        terraform plan
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    paths: terraform/*
  - !BranchUpdateTrigger
    branches: main
  - !PullRequestUpdateTrigger
    branches: main
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: terraform-apply
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: true
    withSubmodules: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: terraform-apply
    runInContainer: true
    image: hashicorp/terraform:1.10
    interpreter: !DefaultInterpreter
      commands: |
        export TF_INPUT="false"
        export TF_IN_AUTOMATION="true"
        export TF_TOKEN_app_terraform_io="@secret:tf-token@"
        export TF_VAR_cloudflare_token="@secret:cloudflare-token@"
        export TF_VAR_cloudflare_account_id="@secret:cloudflare-account-id@"
        export TF_VAR_cloudflare_zone_id="@secret:cloudflare-zone-id@"

        cd terraform
        terraform init &&
        terraform apply -auto-approve
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: main
  jobDependencies:
  - jobName: terraform-plan
    requireSuccessful: true
    artifacts: '**'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: docker-build-homepage
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: true
    withSubmodules: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: ls
    runInContainer: true
    image: busybox
    interpreter: !DefaultInterpreter
      commands: |
        ls -al
        la -al hugo/
        ls -al hugo/public/
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !BuildImageStep
    name: docker-build-homepage
    buildPath: hugo/
    output: !RegistryOutput
      tags: '@server_host@/maxmorris.io/homepage:latest'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: main
  jobDependencies:
  - jobName: hugo-build-homepage
    requireSuccessful: true
    artifacts: '**'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: hugo-build-homepage
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: true
    withSubmodules: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: hugo-build
    runInContainer: true
    image: hugomods/hugo:exts-0.111.3
    interpreter: !DefaultInterpreter
      commands: |
        cd hugo
        hugo -d public && tar -cvf public.tar public/
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: public-artifact
    sourcePath: hugo
    artifacts: public.tar
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: main
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
