version: 38
imports:
- projectPath: morrislan
  revision: prod
jobs:
- name: github-mirror
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: true
    withSubmodules: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PushRepository
    name: push-to-github
    remoteUrl: https://github.com/m4xmorris/maxmorris.io
    passwordSecret: github-pat
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: build-site-docker
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: true
    withSubmodules: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !BuildImageStep
    name: docker-build
    output: !RegistryOutput
      tags: '@server_host@/maxmorris.io/site:latest'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: main
  jobDependencies:
  - jobName: build-site-hugo
    requireSuccessful: true
    artifacts: '**'
    destinationPath: hugo/public
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: build-site-hugo
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: true
    withSubmodules: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: hugo-build
    runInContainer: true
    image: hugomods/hugo:exts-0.140.0
    interpreter: !DefaultInterpreter
      commands: |
        cd hugo
        hugo -d public
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: export-html
    sourcePath: hugo/public
    artifacts: '**'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: main
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
