name: "Build maxmorris.io"

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hugo:
    name: "Hugo"
    runs-on: ubuntu-latest
    container:
      image: hugomods/hugo:exts-0.140.0
    defaults:
      run:
        working-directory: ./hugo
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Hugo Build
        run: hugo -d public
      
      - name: Export HTML
        uses: actions/upload-artifact@v3
        with:
          name: html
          path: hugo/public
          if-no-files-found: error
          retention-days: 7

  podman:
    name: "Podman Build"
    runs-on: ubuntu-latest
    container:
      image: git.morrislan.net/morrislan/podman-action:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get HTML
        uses: actions/download-artifact@v3
        with:
          name: html
          path: hugo/public

      - name: Import Secrets
        uses: hashicorp/vault-action@v3
        with:
          url: https://vault.morrislan.net
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secrets/data/gitea ci-docker-token | DOCKER_TOKEN ;            

      - name: Login to Registry
        run: echo ${{ env.DOCKER_TOKEN }} | podman login git.morrislan.net --username morrislan-gitea --password-stdin

      - name: Build
        run: podman build /workspace/max/maxmorris.io -t git.morrislan.net/max/maxmorris.io:${{ github.sha }}

      - name: Push
        if: github.ref == 'refs/heads/main'
        run: podman push git.morrislan.net/max/maxmorris.io:${{ github.sha }}

      - name: Push latest
        if: github.ref == 'refs/heads/main'
        run: |
          podman tag git.morrislan.net/max/maxmorris.io:${{ github.sha }} git.morrislan.net/max/maxmorris.io:latest
          podman push git.morrislan.net/max/maxmorris.io:latest