name: "Terraform"

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"

jobs:
  plan:
    name: "Plan"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    env:
      TF_VAR_cloudflare_zone_id: "${{ secrets.CLOUDFLARE_ZONE_ID }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import Secrets
        uses: hashicorp/vault-action@v3
        with:
          url: https://vault.morrislan.net
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secrets/data/tf-cloud token | TF_TOKEN_app_terraform_io ;
            secrets/data/cloudflare token | TF_VAR_cloudflare_token ;
            secrets/data/cloudflare account-id | TF_VAR_cloudflare_account_id ;
            secrets/data/do spaces-access-key-id | AWS_ACCESS_KEY_ID ;
            secrets/data/do spaces-secret-access-key | AWS_SECRET_ACCESS_KEY ;

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Format Check
        id: fmt-check
        run: terraform fmt -check

      - name: Initialize
        id: init
        run: terraform init

      - name: Validate
        id: validate
        run: terraform validate

      - name: Plan
        run: terraform plan

  apply:
    name: "Apply"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: terraform-plan
    defaults:
      run:
        working-directory: ./terraform
    env:
      TF_VAR_cloudflare_zone_id: "${{ secrets.CLOUDFLARE_ZONE_ID }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import Secrets
        uses: hashicorp/vault-action@v3
        with:
          url: https://vault.morrislan.net
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secrets/data/tf-cloud token | TF_TOKEN_app_terraform_io ;
            secrets/data/cloudflare token | TF_VAR_cloudflare_token ;
            secrets/data/cloudflare account-id | TF_VAR_cloudflare_account_id ;

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize
        id: init
        run: terraform init

      - name: Apply
        run: terraform apply -auto-approve