apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maxmorris-io
  namespace: argocd
spec:
  project: default
  sources:
     - repoURL: 'https://github.com/m4xmorris/maxmorris.io'
       targetRevision: main
       path: 'k8s'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: maxmorris-io
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
