module "do_apps_tf" {
	source = "github.com/maxmorrisio/do-apps-tf.git?ref=dev"
	site_name = "maxmorrisio-dev"
	description = "Personal Website"
	environment = "Development"
	region = "lon"
	domain = "dev.maxmorris.io"
	source_repo = "maxmorrisio/personal-site"
	source_branch = "dev"
	source_dir = "hugo"
	output_dir = "public"
	build_command = "hugo -d public"
	cloudflare_zone_id = "${var.cloudflare_zone_id}"
	cloudflare_token = "${var.cloudflare_token}"
	do_token = "${var.do_token}"
}
